import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Sidebar from "@/components/layout/Sidebar/Sidebar";
import MainWrapper from "@/components/layout/MainWrapper";
import StoreProvider from "@/providers/StoreProvider";
import { ReactNode } from "react";
import { Toaster } from "sonner";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vidflow",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "";

    return (
        <html lang="en" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {}
        <GoogleOAuthProvider clientId={googleClientId}>
            <StoreProvider>
                <Header />
                <Sidebar />

                <MainWrapper>
                    {children}
                    <Toaster theme="dark" position="bottom-center" />
                </MainWrapper>
            </StoreProvider>
        </GoogleOAuthProvider>
        </body>
        </html>
    );
}